Update botssh

diff --git a/Modulos/botssh b/Modulos/botssh
--- a/Modulos/botssh
+++ b/Modulos/botssh
@@ -30,12 +30,12 @@ tput cnorm
 fun_botOnOff () {
       [[ $(ps x | grep "bot_plus"|grep -v grep | wc -l) = '0' ]] && {
           clear
-          echo -e "\E[44;1;37m             INSTALADOR BOT SSHPLUS                \E[0m\n"
-          echo -ne "\033[1;32mINFORME SEU TOKEN:\033[1;37m "; read tokenbot
+          echo -e "\E[44;1;37m             BOT DARKSSH INSTALLER                \E[0m\n"
+          echo -ne "\033[1;32mINFORM YOUR TOKEN:\033[1;37m "; read tokenbot
   	    echo ""
-  	    echo -ne "\033[1;32mINFORME SEU ID:\033[1;37m "; read iduser
+  	    echo -ne "\033[1;32mINFORM YOUR ID:\033[1;37m "; read iduser
           clear
-          echo -e "\033[1;32mINICIANDO BOT SSHPLUS \033[0m\n"
+          echo -e "\033[1;32mSTARTING DARKSSH BOT \033[0m\n"
           fun_bot1 () {
   	        [[ ! -e "/etc/SSHPlus/ShellBot.sh" ]] && wget -qO- https://raw.githubusercontent.com/shellscriptx/shellbot/master/ShellBot.sh > /etc/SSHPlus/ShellBot.sh
   	        cd /etc/SSHPlus
@@ -50,12 +50,12 @@ fun_botOnOff () {
   	        cd $HOME
           }
           fun_bar 'fun_bot1'
-          [[ $(ps x | grep "bot_plus"|grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m BOT SSHPLUS ATIVADO !\033[0m" || echo -e "\n\033[1;31m ERRO! REANALISE SUAS INFORMACOES\033[0m"
+          [[ $(ps x | grep "bot_plus"|grep -v grep | wc -l) != '0' ]] && echo -e "\n\033[1;32m DARKSSH BOT ON !\033[0m" || echo -e "\n\033[1;31m ERROR! RE-ANALYZE YOUR INFORMATION\033[0m"
           sleep 3
           menu
       } || {
           clear
-          echo -e "\033[1;32mPARANDO BOT SSHPLUS... \033[0m\n"
+          echo -e "\033[1;32mSTOPPING BOT DARKSSH ... \033[0m\n"
           fun_bot2 () {
               screen -r -S "bot_plus" -X quit
               screen -wipe 1>/dev/null 2>/dev/null
@@ -66,25 +66,25 @@ fun_botOnOff () {
               sleep 1
           }
           fun_bar 'fun_bot2'
-          echo -e "\n\033[1;32m \033[1;31mBOT SSHPLUS PARADO! \033[0m"
+          echo -e "\n\033[1;32m \033[1;31mDARKSSH BOT STOPPED! \033[0m"
           sleep 3
           menu
       }
 }
 
 fun_instbot () {
-echo -e "\E[44;1;37m             INSTALADOR BOT SSHPLUS                \E[0m\n"
-echo -e "                 \033[1;33m[\033[1;31m!\033[1;33m] \033[1;31mATENCAO \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
-echo -e "\n\033[1;32m1° \033[1;37m- \033[1;33mPELO SEU TELEGRAM ACESSE OS SEGUINTES BOT\033[1;37m:\033[0m"
-echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;33mCRIE O SEU BOT \033[1;31mOPCAO: \033[1;37m/newbot\033[0m"
-echo -e "\n\033[1;32m3° \033[1;37m- \033[1;33mBOT \033[1;37m@EdRobot \033[1;33mE PEGUE SEU ID \033[1;31mOPCAO: \033[1;37m/id\033[0m"
+echo -e "\E[44;1;37m             BOT SSHPLUS INSTALLER                \E[0m\n"
+echo -e "                 \033[1;33m[\033[1;31m!\033[1;33m] \033[1;31mATTENTION \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
+echo -e "\n\033[1;32m1° \033[1;37m- \033[1;33mBY YOUR TELEGRAM ACCESS THE FOLLOWING BOT\033[1;37m:\033[0m"
+echo -e "\n\033[1;32m2° \033[1;37m- \033[1;33mBOT \033[1;37m@BotFather \033[1;33mCREATE YOUR BOT \033[1;31mOPTION: \033[1;37m/newbot\033[0m"
+echo -e "\n\033[1;32m3° \033[1;37m- \033[1;33mBOT \033[1;37m@my_id_bot \033[1;33mAND GET YOUR ID \033[1;31mOPTION: \033[1;37m/id\033[0m"
 echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[1;32m"
 echo ""
 read -p "DESEJA CONTINUAR ? [s/n]: " -e -i n resposta
 if [[ "$resposta" = 's' ]]; then
   	fun_botOnOff
   else
-      echo -e "\n\033[1;31mRetornando...\033[0m"
+      echo -e "\n\033[1;31mReturning ...\033[0m"
       sleep 3
       menu
 fi
