Update conexao

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -1,5 +1,11 @@
 #!/bin/bash
-
+#====================================================
+#	SCRIPT: CONEXAO SSHPLUS MANAGER
+#	DESENVOLVIDO POR:	CRAZY_VPN
+#	DATA ATUALIZACAO:	28-04-2021 
+#	CONTATO TELEGRAM:	http://t.me/crazy_vpn
+#	contact me:	http://t.me/sibatro
+#====================================================
 [[ $(awk -F" " '{print $2}' /usr/lib/licence) == "@CRAZY_VPN" ]] && {
 	ram1=$(free -h | grep -i mem | awk {'print $2'})
 	ram2=$(free -h | grep -i mem | awk {'print $4'})
@@ -17,7 +23,7 @@
 			touch $HOME/fim
 		) >/dev/null 2>&1 &
 		tput civis
-		echo -ne "\033[1;33mPLEASE WAIT... \033[1;37m- \033[1;33m["
+		echo -ne "\033[1;33mHOLD \033[1;37m- \033[1;33m["
 		while true; do
 			for ((i = 0; i < 18; i++)); do
 				echo -ne "\033[1;31m#"
@@ -28,7 +34,7 @@
 			sleep 1s
 			tput cuu1
 			tput dl1
-			echo -ne "\033[1;33mPLEASE WAIT... \033[1;37m- \033[1;33m["
+			echo -ne "\033[1;33mHOLD \033[1;37m- \033[1;33m["
 		done
 		echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
 		tput cnorm
@@ -90,7 +96,7 @@
 			echo -ne "\033[1;32mTO CONTINUE CONFIRM YOUR IP: \033[1;37m"
 			read -e -i $IP ipdovps
 			[[ -z "$ipdovps" ]] && {
-				echo -e "\n\033[1;31mInvalid IP\033[1;32m"
+				echo -e "\n\033[1;31mIP invalido\033[1;32m"
 				echo ""
 				read -p "Enter your IP: " IP
 			}
@@ -893,55 +899,55 @@
 					;;
 				5)
 					clear
-					echo -e "\E[44;1;37m         CHANGE DNS HOST           \E[0m"
+					echo -e "\E[44;1;37m         ALTERAR HOST DNS           \E[0m"
 					echo ""
-					echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mADD HOST DNS"
-					echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mREMOVE HOST DNS"
-					echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mEDIT MANUALLY"
-					echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mCOME BACK"
+					echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mADICIONAR HOST DNS"
+					echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mREMOVER HOST DNS"
+					echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mEDITAR MANUALMENTE"
+					echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR"
 					echo ""
-					echo -ne "\033[1;32mWHAT DO YOU WANT TO DO \033[1;33m?\033[1;31m?\033[1;37m "
+					echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m "
 					read resp
 					[[ -z "$resp" ]] && {
 						echo ""
-						echo -e "\033[1;31mInvalid option!"
+						echo -e "\033[1;31mOpcao invalida!"
 						sleep 3
 						fun_openvpn
 					}
 					if [[ "$resp" = '1' ]]; then
 						clear
-						echo -e "\E[44;1;37m            Add DNS Host            \E[0m"
+						echo -e "\E[44;1;37m            Adicionar Host DNS            \E[0m"
 						echo ""
-						echo -e "\033[1;33mList of current hosts:\033[0m "
+						echo -e "\033[1;33mLista dos hosts atuais:\033[0m "
 						echo ""
 						i=0
 						for _host in $(grep -w "127.0.0.1" /etc/hosts | grep -v "localhost" | cut -d' ' -f2); do
 							echo -e "\033[1;32m$_host"
 						done
 						echo ""
-						echo -ne "\033[1;33mEnter the host to be added\033[1;37m : "
+						echo -ne "\033[1;33mDigite o host a ser adicionado\033[1;37m : "
 						read host
 						if [[ -z $host ]]; then
 							echo ""
-							echo -e "\E[41;1;37m        Empty or invalid field !       \E[0m"
+							echo -e "\E[41;1;37m        Campo Vazio ou invalido !       \E[0m"
 							sleep 2
 							fun_openvpn
 						fi
 						if [[ "$(grep -w "$host" /etc/hosts | wc -l)" -gt "0" ]]; then
-							echo -e "\E[41;1;37m    This host is already added  !    \E[0m"
+							echo -e "\E[41;1;37m    Esse host ja está adicionado  !    \E[0m"
 							sleep 2
 							fun_openvpn
 						fi
 						sed -i "3i\127.0.0.1 $host" /etc/hosts
 						echo ""
-						echo -e "\E[44;1;37m      Host added successfully!      \E[0m"
+						echo -e "\E[44;1;37m      Host adicionado com sucesso !      \E[0m"
 						sleep 2
 						fun_openvpn
 					elif [[ "$resp" = '2' ]]; then
 						clear
-						echo -e "\E[44;1;37m            DNS Host Remover            \E[0m"
+						echo -e "\E[44;1;37m            Remover Host DNS            \E[0m"
 						echo ""
-						echo -e "\033[1;33mList of current hosts:\033[0m "
+						echo -e "\033[1;33mLista dos hosts atuais:\033[0m "
 						echo ""
 						i=0
 						for _host in $(grep -w "127.0.0.1" /etc/hosts | grep -v "localhost" | cut -d' ' -f2); do
@@ -952,11 +958,11 @@
 							echo -e "\033[1;33m[\033[1;31m$i\033[1;33m] \033[1;37m- \033[1;32m$_host\033[0m"
 						done
 						echo ""
-						echo -ne "\033[1;32mSelect the host to be removed \033[1;33m[\033[1;37m1\033[1;31m-\033[1;37m$i\033[1;33m]\033[1;37m: "
+						echo -ne "\033[1;32mSelecione o host a ser removido \033[1;33m[\033[1;37m1\033[1;31m-\033[1;37m$i\033[1;33m]\033[1;37m: "
 						read option
 						if [[ -z $option ]]; then
 							echo ""
-							echo -e "\E[41;1;37m          Invalid option  !        \E[0m"
+							echo -e "\E[41;1;37m          Opcao invalida  !        \E[0m"
 							sleep 2
 							fun_openvpn
 						fi
@@ -964,27 +970,27 @@
 						hst=$(grep -v "127.0.0.1 $host" /etc/hosts)
 						echo "$hst" >/etc/hosts
 						echo ""
-						echo -e "\E[41;1;37m      Host removed successfully !      \E[0m"
+						echo -e "\E[41;1;37m      Host removido com sucesso !      \E[0m"
 						sleep 2
 						fun_openvpn
 					elif [[ "$resp" = '3' ]]; then
-						echo -e "\n\033[1;32mCHANGING FILE \033[1;37m/etc/hosts\033[0m"
-						echo -e "\n\033[1;31mATTENTION!\033[0m"
-						echo -e "\n\033[1;33mTO SAVE USE KEYS \033[1;32mctrl x y\033[0m"
+						echo -e "\n\033[1;32mALTERANDO ARQUIVO \033[1;37m/etc/hosts\033[0m"
+						echo -e "\n\033[1;31mATENCAO!\033[0m"
+						echo -e "\n\033[1;33mPARA SALVAR USE AS TECLAS \033[1;32mctrl x y\033[0m"
 						sleep 4
 						clear
 						nano /etc/hosts
-						echo -e "\n\033[1;32mSUCCESSFULLY CHANGED!\033[0m"
+						echo -e "\n\033[1;32mALTERADO COM SUCESSO!\033[0m"
 						sleep 3
 						fun_openvpn
 					elif [[ "$resp" = '0' ]]; then
 						echo ""
-						echo -e "\033[1;31mreturning...\033[0m"
+						echo -e "\033[1;31mRetornando...\033[0m"
 						sleep 2
 						fun_conexao
 					else
 						echo ""
-						echo -e "\033[1;31mInvalid option!\033[0m"
+						echo -e "\033[1;31mOpcao invalida !\033[0m"
 						sleep 2
 						fun_openvpn
 					fi
@@ -994,7 +1000,7 @@
 					;;
 				*)
 					echo ""
-					echo -e "\033[1;31mInvalid option !\033[0m"
+					echo -e "\033[1;31mOpcao invalida !\033[0m"
 					sleep 2
 					fun_openvpn
 					;;
@@ -1002,28 +1008,28 @@
 			done
 		} || {
 			clear
-			echo -e "\E[44;1;37m              OPENVPN INSTALLER               \E[0m"
+			echo -e "\E[44;1;37m              INSTALADOR OPENVPN               \E[0m"
 			echo ""
-			echo -e "\033[1;33mANSWER THE QUESTIONS TO START THE INSTALLATION"
+			echo -e "\033[1;33mRESPONDA AS QUESTOES PARA INICIAR A INSTALACAO"
 			echo ""
-			echo -ne "\033[1;32mTO CONTINUE CONFIRM YOUR IP: \033[1;37m"
+			echo -ne "\033[1;32mPARA CONTINUAR CONFIRME SEU IP: \033[1;37m"
 			read -e -i $IP IP
 			[[ -z "$IP" ]] && {
 				echo ""
-				echo -e "\033[1;31mInvalid IP!"
+				echo -e "\033[1;31mIP invalido!"
 				sleep 3
 				fun_conexao
 			}
 			echo ""
-			read -p "$(echo -e "\033[1;32mWHICH PORT DO YOU WANT TO USE? \033[1;37m")" -e -i 1194 porta
+			read -p "$(echo -e "\033[1;32mQUAL PORTA DESEJA UTILIZAR? \033[1;37m")" -e -i 1194 porta
 			[[ -z "$porta" ]] && {
 				echo ""
-				echo -e "\033[1;31mInvalid port!"
+				echo -e "\033[1;31mPorta invalida!"
 				sleep 2
 				fun_conexao
 			}
 			echo ""
-			echo -e "\033[1;33mVERIFYING PORT..."
+			echo -e "\033[1;33mVERIFICANDO PORTA..."
 			verif_ptrs $porta
 			echo ""
 			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;33mSistema"
@@ -1049,14 +1055,14 @@
 			fi
 			echo ""
 			[[ "$OS" = 'debian' ]] && {
-				echo -e "\033[1;32mUPDATING THE SYSTEM"
+				echo -e "\033[1;32mATUALIZANDO O SISTEMA"
 				echo ""
 				fun_attos() {
 					apt-get update-y
 				}
 				fun_bar 'fun_attos'
 				echo ""
-				echo -e "\033[1;32mINSTALLING DEPENDENCES"
+				echo -e "\033[1;32mINSTALANDO DEPENDENCIAS"
 				echo ""
 				fun_instdep() {
 					apt-get install openvpn iptables openssl ca-certificates -y
@@ -1087,7 +1093,7 @@
 				./easyrsa --batch build-ca nopass
 				./easyrsa gen-dh
 				./easyrsa build-server-full server nopass
-				./easyrsa build-client-full VPSMANAGER nopass
+				./easyrsa build-client-full SSHPLUS nopass
 				./easyrsa gen-crl
 				cp pki/ca.crt pki/private/ca.key pki/dh.pem pki/issued/server.crt pki/private/server.key /etc/openvpn/easy-rsa/pki/crl.pem /etc/openvpn
 				chown nobody:$GROUPNAME /etc/openvpn/crl.pem
@@ -1194,7 +1200,7 @@ exit 0' >$RCLOCAL
 					fi
 				fi
 			}
-			echo -e "\033[1;32mINSTALLING OPENVPN \033[1;31m(\033[1;33mPODE DEMORAR!\033[1;31m)"
+			echo -e "\033[1;32mINSTALANDO O OPENVPN  \033[1;31m(\033[1;33mPODE DEMORAR!\033[1;31m)"
 			echo ""
 			fun_bar 'fun_dep > /dev/null 2>&1'
 			fun_ropen() {
@@ -1215,7 +1221,7 @@ exit 0' >$RCLOCAL
 				}
 			}
 			echo ""
-			echo -e "\033[1;32mRESTARTING OPENVPN"
+			echo -e "\033[1;32mREINICIANDO O OPENVPN"
 			echo ""
 			fun_bar 'fun_ropen'
 			IP2=$(wget -4qO- "http://whatismyip.akamai.com/")
@@ -1248,8 +1254,8 @@ exit 0' >$RCLOCAL
 				float
 			EOF
 			# gerar client.ovpn
-			newclient "VPSMANAGER"
-			[[ "$(netstat -nplt | grep -wc 'openvpn')" != '0' ]] && echo -e "\n\033[1;32mOPENVPN SUCCESSFULLY INSTALLED\033[0m" || echo -e "\n\033[1;31mERRO ! A INSTALACAO CORROMPEU\033[0m"
+			newclient "SSHPLUS"
+			[[ "$(netstat -nplt | grep -wc 'openvpn')" != '0' ]] && echo -e "\n\033[1;32mOPENVPN INSTALADO COM SUCESSO\033[0m" || echo -e "\n\033[1;31mERRO ! A INSTALACAO CORROMPEU\033[0m"
 		}
 		sed -i '$ i\echo 1 > /proc/sys/net/ipv4/ip_forward' /etc/rc.local
 		sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.local
@@ -1299,22 +1305,22 @@ exit 0' >$RCLOCAL
 					sleep 1
 					screen -wipe >/dev/null
 				}
-				echo -e "\033[1;32mDISABLING PROXY SOCKS\033[1;33m"
+				echo -e "\033[1;32mDESATIVANDO O PROXY SOCKS\033[1;33m"
 				echo ""
 				fun_bar 'fun_socksoff'
 				echo ""
-				echo -e "\033[1;32mPROXY SOCKS SUCCESSFULLY DISABLED!\033[1;33m"
+				echo -e "\033[1;32mPROXY SOCKS DESATIVADO COM SUCESSO!\033[1;33m"
 				sleep 3
 				fun_socks
 			else
 				clear
 				echo -e "\E[44;1;37m             PROXY SOCKS              \E[0m"
 				echo ""
-				echo -ne "\033[1;32mWHICH PORT YOU WANT TO USE \033[1;33m?\033[1;37m: "
+				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m: "
 				read porta
 				[[ -z "$porta" ]] && {
 					echo ""
-					echo -e "\033[1;31mInvalid port!"
+					echo -e "\033[1;31mPorta invalida!"
 					sleep 3
 					clear
 					fun_conexao
@@ -1331,11 +1337,11 @@ exit 0' >$RCLOCAL
 					}
 				}
 				echo ""
-				echo -e "\033[1;32mSTARTING PROXY SOCKS\033[1;33m"
+				echo -e "\033[1;32mINICIANDO O PROXY SOCKS\033[1;33m"
 				echo ""
 				fun_bar 'fun_inisocks'
 				echo ""
-				echo -e "\033[1;32mSOCKS SUCCESSFULLY ACTIVATED\033[1;33m"
+				echo -e "\033[1;32mSOCKS ATIVADO COM SUCESSO\033[1;33m"
 				sleep 3
 				fun_socks
 			fi
